[target.thumbv7m-none-eabi] # <-change for your platform
runner = 'probe-rs run --chip STM32F103C8' # <- change for your chip
# rustflags = ["-C", "link-arg=-Tlink.x"]

[build]
target = "thumbv7m-none-eabi" # <-change for your platform

[env]
DEFMT_LOG = "trace" # <- can change to info, warn, or error
